### ISSUE TITLE
LAB-1

### ISSUE THREAD

**Issue by cuongtvee** [18520474/AnhAnh#1]
- Bổ sung kiến sơ đồ Diagram
- Mô phỏng với nhiều trường hợp valid_in thay đổi
- Báo cáo kết quả synthesis: resource, clock rate ..
- report theo mẫu: https://drive.google.com/file/d/0Bwb9L1bLDoMbNjIwT1hyU21nWUU/view

**Comment by 18520474** [comment]
Em đã bổ sung
